# -*- coding: utf-8 -*-
{
    "name": "Configurateur de menuiserie aluminium",
    "version": "19.0.1.0.0",
    "summary": "Configurateur phase 1 pour catalogue, calcul, devis et liaisons de production en menuiserie aluminium",
    "category": "Sales/Sales",
    "author": "OpenAI",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "portal",
        "product",
        "uom",
        "web",
        "sale_management",
        "sale_project",
        "mrp",
        "sale_mrp",
        "project_mrp",
    ],
    "data": [
        "security/aluminium_joinery_security.xml",
        "security/ir.model.access.csv",
        "data/aluminium_joinery_sequence.xml",
        "views/aluminium_joinery_catalog_views.xml",
        "views/aluminium_joinery_configuration_views.xml",
        "views/aluminium_joinery_import_views.xml",
        "views/product_views.xml",
        "views/sale_order_views.xml",
        "views/project_views.xml",
        "views/mrp_views.xml",
        "views/aluminium_joinery_menu.xml",
        "views/aluminium_joinery_portal_templates.xml",
        "report/aluminium_joinery_reports.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "aluminium_joinery_configurator/static/src/scss/joinery_portal.scss",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
